---
title: "MarioKart8"
subtitle: "world championship"
output: html_notebook
---


```{r setup}
# tidyverse
library(tidyverse)
library(glue)
library(lubridate)
library(readxl)


# utilities
library(janitor)
library(googlesheets4)
library(RcppRoll) 

# run `gs4_auth()` in the console to set google authorization
# - see https://googlesheets4.tidyverse.org/reference/gs4_auth.html for details


```


```{r}
# local copy
#df_playlist <- read_excel("music playlist.xlsx")


# read from google sheets

mariokart_file <- "https://docs.google.com/spreadsheets/d/1OoDAJMd8ag_W7DtRXyVsfx2VrQes4LqCDYhuLldUwuU/edit?usp=sharing"


#df_playlist <- read_sheet(music_playlist)
df_mk_source <- read_sheet(mariokart_file, sheet = "RaceResults")

df_mk_source

```



## race wins


```{r}

df_mk <- df_mk_source %>% 
  mutate(head_to_head = case_when(
    Jamie < Martin ~ "J",
    TRUE ~ "M"
  ))


df_mk <- df_mk %>% 
  mutate(J_win = case_when(
    head_to_head == "J" ~ 1,
    TRUE ~ as.double(0)
  )) %>% 
  mutate(M_win = case_when(
    head_to_head == "M" ~ 1,
    TRUE ~ as.double(0)
  ))  

df_mk <- df_mk %>% 
  mutate(J_cum_wins = cumsum(J_win),
         M_cum_wins = cumsum(M_win)) %>% 
  mutate(win_diff = J_cum_wins - M_cum_wins,
                  race_count = 1:n())

df_mk
```


```{r}

plotdate <- as_date(today())


mround <- function(x,base){
        base*ceiling(x/base)
}

scale_length <- mround(max(df_mk$J_cum_wins), 5)

ggplot(df_mk, aes(x = J_cum_wins, y = M_cum_wins)) +
  geom_line(colour = "red", size = 1.5) +
  geom_abline(intercept = 0) +
  coord_fixed() +
  labs(title = "MarioKart8 World Championship",
       subtitle = glue("cumulative wins to ", {format(plotdate, "%Y-%m-%d")})) +
  xlab("Jamie: cumulative wins") +
  ylab("Martin: cumulative wins") +
  scale_y_continuous(breaks = seq(0, scale_length, 10)) +
  scale_x_continuous(breaks = seq(0, scale_length, 10)) 
  

  # ggsave("cumulative_wins.jpg")

```



```{r}

races_run <- max(df_mk$race_count)

ggplot(df_mk, aes(x = race_count, y = win_diff)) +
  geom_line(colour = "red", size = 1.5) +
  annotate("segment", x = 0, xend = races_run, y = 0, yend = 0) +
  labs(title = "MarioKart8 World Championship",
       subtitle = glue("win differential to ", {format(plotdate, "%Y-%m-%d")})) +
  xlab("race number") +
  ylab("win differential: Jamie's wins lead")
  

#  ggsave("cumulative_points.jpg")


```

## points

calculate points based on rank


```{r}

df_mk_long <- df_mk_source %>% 
  pivot_longer(cols = c(Jamie, Martin),
               names_to = "racer", values_to = "race_rank")

df_mk_long

```

```{r}

rank_to_point <- tibble::tribble(
  ~rank, ~points,
   1L, 15L,
   2L, 12L,
   3L, 10L,
   4L,  9L,
   5L,  8L,
   6L,  7L,
   7L,  6L,
   8L,  5L,
   9L,  4L,
  10L,  3L,
  11L,  2L,
  12L,  1L
  )


```

```{r}

df_mk_long <- df_mk_long %>% 
  left_join(rank_to_point, by = c("race_rank" = "rank"))
df_mk_long

```


```{r}

df_mk_long %>% 
  group_by(racer) %>% 
  summarise(total_points = sum(points))

```


```{r}

df_mk_long <- df_mk_long %>% 
  group_by(racer) %>% 
  mutate(cum_pts = cumsum(points)) %>% 
  ungroup()

df_mk_long

df_mk_cum_pts <- df_mk_long %>% 
  select(c(race_date:racer), cum_pts) %>% 
  pivot_wider(names_from = racer,
              values_from = cum_pts) %>% 
  mutate(pt_diff = Jamie - Martin,
         race_count = 1:n())

df_mk_cum_pts

```

```{r}

plotdate <- as_date(today())

ggplot(df_mk_cum_pts, aes(x = Jamie, y = Martin)) +
  geom_line(colour = "red", size = 1.5) +
  geom_abline(intercept = 0) +
  coord_fixed() +
  labs(title = "MarioKart8 World Championship",
       subtitle = glue("cumulative points to ", {format(plotdate, "%Y-%m-%d")})) +
  xlab("Jamie: cumulative points") +
  ylab("Martin: cumulative points")
  

  ggsave("cumulative_points.jpg")

```

```{r}

races_run <- max(df_mk_cum_pts$race_count)

ggplot(df_mk_cum_pts, aes(x = race_count, y = pt_diff)) +
  geom_line(colour = "red", size = 1.5) +
  annotate("segment", x = 0, xend = races_run, y = 0, yend = 0) +
  labs(title = "MarioKart8 World Championship",
       subtitle = glue("point differential to ", {format(plotdate, "%Y-%m-%d")})) +
  xlab("race number") +
  ylab("point differential: Jamie's point lead")
  

#  ggsave("cumulative_points.jpg")


```

## track


```{r}

df_mk_long %>% 
  group_by(track, racer) %>% 
  summarise(total_points = sum(points))

```

```{r}

track_tally <- df_mk_long %>% 
  mutate(one = 1) %>% 
  group_by(track, racer) %>% 
  summarise(total_points = sum(points),
         race_count = sum(one)/2) %>%
  pivot_wider(id_cols = track, names_from = racer, values_from = c(total_points, race_count)) %>% 
  mutate(point_differential = total_points_Jamie - total_points_Martin,
         race_count = race_count_Jamie + race_count_Martin) %>% 
  select(-c(race_count_Jamie, race_count_Martin)) 

track_tally %>% 
  arrange(desc(point_differential))

track_tally %>% 
  arrange(race_count)

```


```{r}

knitr::kable(track_tally)

```



```{r}

DT::datatable(track_tally)

```