---
title: "MarioKart8"
subtitle: "world championship"
output: 
  html_document:
    toc: true
    toc_depth: 2
---


```{r setup, include = FALSE}
# tidyverse
library(tidyverse)
library(glue)
library(lubridate)
library(readxl)
library(magrittr)


# utilities
library(janitor)
library(googlesheets4)
library(RcppRoll) 

# run `gs4_auth()` in the console to set google authorization
# - see https://googlesheets4.tidyverse.org/reference/gs4_auth.html for details

mk8_palette <- c("#e72020", "#28cae1", "#4de32a", "#f477dc", "#fbf230")

```


Latest results (as of `r today()`)

```{r include = FALSE}
# local copy
#df_playlist <- read_excel("music playlist.xlsx")


# read from google sheets

mariokart_file <- "https://docs.google.com/spreadsheets/d/1OoDAJMd8ag_W7DtRXyVsfx2VrQes4LqCDYhuLldUwuU/edit?usp=sharing"


## read race results

df_mk_source <- read_sheet(mariokart_file, sheet = "RaceResults")

df_mk_source %<>% 
  mutate(track = as.factor(track))  # use base R `as.factor` so that they show up in alphabetical order

## check track spellings in race results file

levels(df_mk_source$track)


## read other sheets

df_cup_source <- read_sheet(mariokart_file, sheet = "CupResults")

df_cup_source

df_cup_track <- read_sheet(mariokart_file, sheet = "cup_track")

df_cup_track
```



## race head-to-head wins


```{r include = FALSE}

df_mk <- df_mk_source %>% 
  mutate(head_to_head = case_when(
    Jamie < Martin ~ "J",
    TRUE ~ "M"
  ))


df_mk <- df_mk %>% 
  mutate(winner = case_when(
    Jamie == 1 ~ "J",
    Martin == 1 ~ "M",
    TRUE ~ "NPC"
  ))




df_mk <- df_mk %>% 
  mutate(J_h2h = case_when(
    head_to_head == "J" ~ 1,
    TRUE ~ as.double(0)
  )) %>% 
  mutate(M_h2h = case_when(
    head_to_head == "M" ~ 1,
    TRUE ~ as.double(0)
  ))  

df_mk <- df_mk %>% 
  mutate(J_cum_h2h = cumsum(J_h2h),
         M_cum_h2h = cumsum(M_h2h)) %>% 
  mutate(h2h_dif = J_cum_h2h - M_cum_h2h,
                  race_count = 1:n())

df_mk
```


```{r echo = FALSE}

plotdate <- as_date(today())


mround <- function(x,base){
        base*ceiling(x/base)
}

scale_length <- mround(max(df_mk$J_cum_h2h), 5)

ggplot(df_mk, aes(x = J_cum_h2h, y = M_cum_h2h)) +
  geom_line(colour = "red", size = 1.5) +
  geom_abline(intercept = 0) +
  coord_fixed() +
  labs(title = "MarioKart8 World Championship",
       subtitle = glue("cumulative head-to-head victories to ", {format(plotdate, "%Y-%m-%d")})) +
  xlab("Jamie: cumulative head-to-head") +
  ylab("Martin: cumulative head-to-head") +
  scale_y_continuous(breaks = seq(0, scale_length, 100)) +
  scale_x_continuous(breaks = seq(0, scale_length, 100)) 
  

  # ggsave("cumulative_wins.jpg")

```



```{r echo = FALSE}

races_run <- max(df_mk$race_count)

ggplot(df_mk, aes(x = race_count, y = h2h_dif)) +
  geom_line(colour = "red", size = 1.5) +
  annotate("segment", x = 0, xend = races_run, y = 0, yend = 0) +
  labs(title = "MarioKart8 World Championship",
       subtitle = glue("head-to-head differential to ", {format(plotdate, "%Y-%m-%d")})) +
  xlab("race number") +
  ylab("head-to-head differential: Jamie's head-to-head lead")
  

#  ggsave("cumulative_points.jpg")


```

## points

calculate points based on rank


```{r include = FALSE}

df_mk_long <- df_mk_source %>% 
  pivot_longer(cols = c(Jamie, Martin),
               names_to = "racer", values_to = "race_rank")

df_mk_long

```

```{r include = FALSE}

rank_to_point <- tibble::tribble(
  ~rank, ~points,
   1L, 15L,
   2L, 12L,
   3L, 10L,
   4L,  9L,
   5L,  8L,
   6L,  7L,
   7L,  6L,
   8L,  5L,
   9L,  4L,
  10L,  3L,
  11L,  2L,
  12L,  1L
  )



df_mk_long <- df_mk_long %>% 
  left_join(rank_to_point, by = c("race_rank" = "rank"))
df_mk_long

```


```{r include = FALSE}

df_mk_long %>% 
  group_by(racer) %>% 
  summarise(total_points = sum(points))

```


```{r include = FALSE}

df_mk_long <- df_mk_long %>% 
  group_by(racer) %>% 
  mutate(cum_pts = cumsum(points)) %>% 
  ungroup()

df_mk_long

df_mk_cum_pts <- df_mk_long %>% 
  select(c(race_date:racer), cum_pts) %>% 
  pivot_wider(names_from = racer,
              values_from = cum_pts) %>% 
  mutate(pt_diff = Jamie - Martin,
         race_count = 1:n())

df_mk_cum_pts

```

```{r echo = FALSE}

plotdate <- as_date(today())

ggplot(df_mk_cum_pts, aes(x = Jamie, y = Martin)) +
  geom_line(colour = "red", size = 1.5) +
  geom_abline(intercept = 0) +
  coord_fixed() +
  labs(title = "MarioKart8 World Championship",
       subtitle = glue("cumulative points to ", {format(plotdate, "%Y-%m-%d")})) +
  xlab("Jamie: cumulative points") +
  ylab("Martin: cumulative points")
  

#  ggsave("cumulative_points.jpg")

```

```{r echo = FALSE}

races_run <- max(df_mk_cum_pts$race_count)

ggplot(df_mk_cum_pts, aes(x = race_count, y = pt_diff)) +
  geom_line(colour = "red", size = 1.5) +
  annotate("segment", x = 0, xend = races_run, y = 0, yend = 0) +
  labs(title = "MarioKart8 World Championship",
       subtitle = glue("point differential to ", {format(plotdate, "%Y-%m-%d")})) +
  xlab("race number") +
  ylab("point differential: Jamie's point lead")
  

#  ggsave("cumulative_points.jpg")


```

## track: total points


```{r include = FALSE}

df_mk_long %>% 
  group_by(track, racer) %>% 
  summarise(total_points = sum(points))

```


```{r include = FALSE}

track_tally <- df_mk_long %>% 
  mutate(one = 1) %>% 
  group_by(track, racer) %>% 
  summarise(total_points = sum(points),
         race_count = sum(one)/2) %>%
  pivot_wider(id_cols = track, names_from = racer, values_from = c(total_points, race_count)) %>% 
  mutate(J_point_differential = total_points_Jamie - total_points_Martin,
         race_count = race_count_Jamie + race_count_Martin) %>%
  mutate(J_point_diff_per_race = round((J_point_differential / race_count), 1)) %>% 
  select(-c(race_count_Jamie, race_count_Martin)) %>% 
  relocate(race_count, .after = track)

```


```{r evaluate = FALSE, include = FALSE}

track_tally %>% 
  arrange(desc(J_point_differential))

track_tally %>% 
  arrange(race_count)

```


```{r evaluate = FALSE, include = FALSE}

knitr::kable(track_tally)

```



```{r echo = FALSE}

DT::datatable(track_tally)

```

## track: total wins


Who won the race?

```{r echo = FALSE}
DT::datatable(
df_mk %>% 
  group_by(winner) %>% 
  tally() %>% 
  mutate(pct_of_wins = round((n / sum(n) * 100), 1))
)


```

## track: wins by track

```{r echo = FALSE}

df_track_wins <- 
df_mk %>% 
  group_by(track, winner) %>% 
  tally() %>% 
  pivot_wider(names_from = winner, values_from = n) %>% 
  mutate(J_track_diff = J - M,
         J_pct = round(J / sum(J, M, na.rm = TRUE) * 100, 1), 
         J_pct_total = round(J / sum(J, M, NPC, na.rm = TRUE) * 100, 1)) 


DT::datatable(
df_track_wins)

```


```{r}

df_mk %>% 
  group_by(track, winner) %>% 
  tally() %>% 
  left_join(df_cup_track, by = "track") %>% 
  ggplot(aes(x = n, y = track, colour = winner)) +
  geom_point(size = 1.5) +
  geom_segment(aes(yend = track), xend = 0) 
 

```


```{r}

df_mk %>% 
  group_by(track, winner) %>% 
  tally() %>% 
  left_join(df_cup_track, by = "track") %>% 
  ggplot(aes(x = n, y = fct_reorder(track, n), colour = winner)) +
  geom_point() +
  geom_segment(aes(yend = track), xend = 0) 
 
df_mk %>% 
  group_by(track, winner) %>% 
  tally() %>% 
  left_join(df_cup_track, by = "track") %>% 
  ggplot(aes(x = n, y = fct_rev(track), colour = winner, shape = winner)) +
  geom_point(size = 1.5) +
  geom_segment(aes(yend = track), xend = 0) +
#  scale_colour_manual(values = mk8_palette) +
  theme_minimal() +
  theme(panel.grid.minor = element_blank())

#ggsave("track_wins.jpg", height = 9, width = 6)

```

## cup points


```{r include = FALSE, echo = FALSE}

df_cup_pts <- 
df_mk_long %>% 
  group_by(race_date, cup_grp, racer) %>% 
  summarise(cup_pts = sum(points),
            race_count = n()) %>% 
  filter(race_count == 4) %>% 
  select(-race_count) %>% 
  pivot_wider(names_from = racer,
              values_from = cup_pts) %>% 
  ungroup()


df_cup_pts <-
df_cup_pts %>% 
  left_join(df_cup_source, by = c("race_date", "cup_grp"))

df_cup_pts

```


```{r}

df_cup_pts_l <- df_cup_pts %>% 
  select(race_date, Jamie, Martin) %>% 
  pivot_longer(-race_date, names_to = "racer", values_to = "points") %>% 
  filter(points <= 60)

df_cup_pts_l

```


```{r}
df_cup_pts_l %>% 
  group_by(racer) %>% 
  summarise(mean(points),
            sd(points),
            min(points),
            max(points))


#df_cup_pts_l %>% 
# filter(points < 25)
  
```


### clean-sweep cups

```{r}

df_cup_pts_l %>% 
  filter(points == 60) %>% 
  group_by(racer) %>% 
  tally()

```

clean sweep and squeegie


```{r}

df_cup_pts_l %>% 
  mutate(wintype = case_when(
    points == 60 ~ "sweep",
    points == 57 ~ "squeegie",
    TRUE ~ "polish"
  )) %>% 
  group_by(racer, wintype) %>% 
  tally() %>% 
  pivot_wider(names_from = wintype, values_from = n)

```


```{r}

ggplot(df_cup_pts_l, aes(x = points, colour = racer)) +
  geom_density() +
  xlim(4, 60)

```

